### ISSUE TITLE
Create Action method

### ISSUE THREAD

**Issue by Datti0812** [Inventory-Devops-Fall21/inventory#43]
**As a** developer 
**I need** to implement the Action method that increments and decrements product quantity
**So that** users can increase/decrease quantity

**Details & Assumptions:** 
* The model schema contains the quantity

**Acceptance Criteria:**
* The product quantity should increase/decrease when user invokes the action

```gherkin
Given action method implemented correctly
When some action calls been made on a resource
Then the product quantity should increase/decrease accordingly
```

**Comment by YinWang3026** [comment]
We should be more specific on what the action is going to do
