### ISSUE TITLE
Add new attributes to Inventory Schema and code changes

### ISSUE THREAD

**Issue by Datti0812** [Inventory-Devops-Fall21/inventory#44]
**As a** developer
**I need** to add new attributes to the schema and make code changes
**So that** we can add data to the new attributes and the new changes won't conflict with the code 

**Details & Assumptions:** 
* Important attribute add-ons will give a good structure to the schema 

**Acceptance Criteria:**

```gherkin
Given new features to the schema 
When a customer asks for a product condition or to increment the stock level
Then we return the condition of the product, increment or decrement the stock level according to the input size.
```

**Comment by YinWang3026** [comment]
This can be separated into 2 issues.
