### ISSUE TITLE
Add Query string support to List function

### ISSUE THREAD

**Issue by Datti0812** [Inventory-Devops-Fall21/inventory#46]
**As a** product owner
**I need** to be able to search for an item
**So that** I can search for products based on keywords

**Details & Assumptions:** 
* The list API already exists

**Acceptance Criteria:**

```gherkin
Given a search API
When a query string is entered
Then a list of products with one of the attributes matching the query string should be shown
```

**Comment by hemantreddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/inventory-615259f44be2610017690639/issues/Inventory-Devops-Fall21/inventory/46?planning-poker) with ZenHub @Datti0812 @yantongj @YinWang3026
