### ISSUE TITLE
Creating the BUILD pipeline

### ISSUE THREAD

**Issue by YinWang3026** [Inventory-Devops-Fall21/inventory#49]
**As a** developer
**I need** to automate the build process
**So that** the DevOps pipeline can be created

**Details & Assumptions:** 
* Have code for the application

**Acceptance Criteria:**
* The build pipeline is set up correctly

```gherkin
Given code
When build pipeline activates
Then the application is build using the code
```

**Comment by hemantreddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/inventory-615259f44be2610017690639/issues/Inventory-Devops-Fall21/inventory/49?planning-poker) with ZenHub @Datti0812 @yantongj @YinWang3026
