### ISSUE TITLE
create the TEST pipeline

### ISSUE THREAD

**Issue by YinWang3026** [Inventory-Devops-Fall21/inventory#50]
**As a** developer 
**I need** to build the TEST pipeline in the IBM cloud
**So that** application will be tested before deployment

**Details & Assumptions:** 
* BUILD pipeline is created

**Acceptance Criteria:**
* Working TEST pipeline

```gherkin
Given the application
When it passes through the TEST pipeline
Then the test result should be ready
```

**Comment by hemantreddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/inventory-615259f44be2610017690639/issues/Inventory-Devops-Fall21/inventory/50?planning-poker) with ZenHub @Datti0812 @yantongj @YinWang3026
